### ISSUE TITLE
**Functionality Checklist*

### ISSUE THREAD

**Issue by cowens87** [smcunning/battleship#17]
Main Menu:
- [x] User is shown the main menu where they can play or quit 

Setup:
- [x] Computer can place ships randomly in valid locations
- [x] User can enter valid sequences to place both ships
- [x] Entering invalid ship placements prompts user to enter valid placements

Turn:
- [x] User board is displayed showing hits, misses, sunken ships, and ships 
- [x] Computer board is displayed showing hits, misses, and sunken ships (**REMOVE** 'true' from computer_board.render)
- [x] Computer chooses a random shot
- [x] Computer does not fire on the same spot twice
- [x] User can choose a valid coordinate to fire on
- [x] Entering invalid coordinate prompts user to enter valid coordinate
- [x] Both computer and player shots are reported as a hit, sink, or miss
- [x] User is informed when they have already fired on a coordinate
- [x] Board is updated after a turn

End Game:
- [x] Game ends when all the computer’s ships are sunk
- [x] Game reports who won
- [x] Game returns user back to the Main Menu
